id: docker-registry-browser-detect

info:
  name: Docker Registry Browser - Detect
  author: pussycat0x
  severity: info
  description: |
    Detected the presence of Docker Registry Browser technology based on known paths and characteristic content in the HTTP response.
  reference:
    - https://github.com/klausmeyer/docker-registry-browser
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Docker Registry Browser"
  tags: docker,registry,browser,ui,tech,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<title>Docker Registry Browser</title>"

      - type: status
        status:
          - 200
# digest: 4a0a004730450221009250788213e8b0e7998c6cbb7f990a5134dcd1c5e2e6f0652b07b29fc36a1d1c02204a5c811d2e2b3ac66892a8b5c3e467413e24ba60c3442ae9983acc9b2005b466:922c64590222798bb761d5b6d8e72950