id: prodigy_commerce-de255530-6b2d-426b-9f80-dbfebd2e3307

info:
  name: >
    Prodigy Commerce <= 3.2.9 - Unauthenticated Local File Inclusion via parameters[template_name]
  author: topscoder
  severity: critical
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/de255530-6b2d-426b-9f80-dbfebd2e3307?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/prodigy-commerce/"
    google-query: inurl:"/wp-content/plugins/prodigy-commerce/"
    shodan-query: 'http.html:"wp-content/plugins/prodigy-commerce/"'
  tags: cve,wordpress,wp-plugin,prodigy-commerce,critical,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/prodigy-commerce/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "prodigy-commerce"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.2.9')