id: td_composer-5fb3a347-e124-484b-9eff-281a10c25a5c

info:
  name: >
    tagDiv Composer <= 5.4.1 - Unauthenticated Stored Cross-Site Scripting
  author: topscoder
  severity: high
  description: >
    
  reference:
    - https://github.com/topscoder/nuclei-wordfence-cve
    - https://www.wordfence.com/threat-intel/vulnerabilities/id/5fb3a347-e124-484b-9eff-281a10c25a5c?source=api-scan
  classification:
    cvss-metrics: 
    cvss-score: 
    cve-id: 
  metadata:
    fofa-query: "wp-content/plugins/td-composer/"
    google-query: inurl:"/wp-content/plugins/td-composer/"
    shodan-query: 'http.html:"wp-content/plugins/td-composer/"'
  tags: cve,wordpress,wp-plugin,td-composer,high,candidate

http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/wp-content/plugins/td-composer/readme.txt"

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - "(?mi)Stable tag:\\s*([0-9.]+)"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "td-composer"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 5.4.1')