name: 🕷 Wordfence crawler

on:
  schedule:
    - cron: '25 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Process vulnerabilities from Wordfence API (production)
        run: |
          python src/main.py --api_endpoint https://www.wordfence.com/api/intelligence/v2/vulnerabilities/production --tag production --clean

      - name: Process vulnerabilities from Wordfence API (scanner)
        run: |
          python src/main.py --api_endpoint https://www.wordfence.com/api/intelligence/v2/vulnerabilities/scanner --tag candidate

      - name: Commit only real content changes (per-file)
        shell: bash
        run: |
          set -euo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config core.filemode false

          differs_from_head() {
            local f="$1"
            if ! git cat-file -e "HEAD:$f" 2>/dev/null; then
              return 0
            fi
            if ! git show "HEAD:$f" | cmp -s - "$f"; then
              return 0
            fi
            return 1
          }

          echo "Commit deleted YAML files (one commit each)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            [[ "$file" == *.yaml || "$file" == *.yml ]] || continue
            git rm -q -- "$file" || true
            git commit -m "Deleted Nuclei template: $(basename "$file") 🤖"
          done < <(git ls-files --deleted || true)

          echo "Commit new YAML files (only if different from HEAD)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            [[ "$file" == *.yaml || "$file" == *.yml ]] || continue
            if differs_from_head "$file"; then
              git add -- "$file"
              git commit -m "Added new Nuclei template: $(basename "$file") 🤖"
            fi
          done < <(git ls-files --others --exclude-standard || true)

          echo "Commit updated YAML files (only if bytes differ from HEAD)..."
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            [[ "$file" == *.yaml || "$file" == *.yml ]] || continue
            [ -f "$file" ] || continue
            if differs_from_head "$file"; then
              git add -- "$file"
              git commit -m "Updated Nuclei template: $(basename "$file") 🤖"
            fi
          done < <(git ls-files || true)

      - name: Push all commits
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
